In [1]:
import numpy as np

In [2]:
np.__version__

'2.3.3'

# numpy 객체 생성

In [ ]:
# 리스트 -> ndarray
a=[1,2,3,4,5]
arr = np.array(a)
arr

array([1, 2, 3, 4, 5])

In [4]:
type(arr)

numpy.ndarray

In [5]:
len(arr)

5

In [6]:
# 튜플 -> ndarray
a=[1,2,3,4,5]
arr = np.array(a)
arr

array([1, 2, 3, 4, 5])

In [7]:
arr.size

5

In [8]:
arr.dtype

dtype('int64')

In [9]:
a=['a',1,2,3,4,5]
arr = np.array(a)
arr

array(['a', '1', '2', '3', '4', '5'], dtype='<U21')

In [10]:
a=[1.0,2,3,4,5]
arr = np.array(a)
arr

array([1., 2., 3., 4., 5.])

# 2차원 데이터 만들기

In [13]:
a2d =[[1,2,3], [3,4,5], [7,8,9]]
a2d

[[1, 2, 3], [3, 4, 5], [7, 8, 9]]

In [14]:
a2d = np.array(a2d)
a2d

array([[1, 2, 3],
       [3, 4, 5],
       [7, 8, 9]])

In [ ]:
# 2차원이기 떄문에 행의 갯수
len(a2d)

3

In [18]:
# array의 전체 요소의 갯수
a2d.size

9

In [19]:
a2d.dtype

dtype('int64')

In [20]:
a2d.shape

(3, 3)

In [21]:
a2d

array([[1, 2, 3],
       [3, 4, 5],
       [7, 8, 9]])

In [ ]:
np.save